version: "3.8"
services:
  app:
    container_name: app
    build:
      context: .
      target: ${TARGET}
    volumes:
      - ./:/opt/todo
    entrypoint: ${ENTRYPOINT}
    ports:
      - 8080:8080
