variable "region" {}
variable "app_name" {}
variable "local_certificate_arn" {}
variable "global_certificate_arn" {}
variable "host_zone_name" {}
variable "sub_domain_name" {}
variable "alb_access_header_name" {}
variable "alb_access_header_value" {}
variable "image_arn" {}
