version: "3.10"
services:
  terraform:
    container_name: "terraform"
    build:
      context: .
      args:
        AWSCLI_VERSION: "2.4.7"
        TERRAFORM_VERSION: "1.1.5"
        TFLINT_VERSION: "v0.24.1"
    volumes:
      - ./:/infrastructure
    tty: true
