name: cicd test, build and deploy

on:
  push:
    branches:
      - development
      - feature/*
    paths:
      - "app/**"
  pull_request:
    branches:
      - development
    paths:
      - "app/**"
  workflow_dispatch:
    inputs:
      job:
        description: "Job to deploy."
        required: true
        default: "deploy"

env:
  SLACK_CHANNEL: github-notification
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  ECS_CLUSTER: todo-app-ecs-cluster
  ECS_SERVICE: todo-app-ecs-service
  ECS_TASK_NAME: todo-app-task
  ECS_CONTAINER_NAME: todo-app
  CODE_DEPLOY_APPLICATION: todo-app-deploy-app
  CODE_DEPLOYMENT_GROUP: todo-app-deployment

permissions:
  id-token: write
  contents: read

jobs:
  static_check:
    if: ${{ github.event.inputs.job != 'deploy'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: go fmt check
        run: |
          cd app
          make fmtcheck
          go test -v ./...

  build:
    if: ${{ github.event.inputs.job != 'deploy'}}
    runs-on: ubuntu-latest
    needs: static_check
    steps:
      - uses: actions/checkout@v2

      - name: Set up docker
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@ea7b857d8a33dc2fb4ef5a724500044281b49a5e
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - uses: docker/login-action@42d299face0c5c43a0487c477f595ac9cf22f1a7
        with:
          registry: ${{ env.ECR_REGISTRY }}

      - name: Build test image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./app
          load: true
          target: build-stage
          tags: build-server:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Test
        # "go test" includes "go vet"", which need C libraries. Alpine container exec this step.
        run: docker run --rm build-server:${{ github.sha }} sh -c "gotest -v -vet=off ./..."

      - name: Build image
        id: build-image
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./app
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # manually deploy, because infrastructure does not always exist to reduce billing cost.

      # - name: Download existing task definition
      #   run: |
      #     aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_NAME }} \
      #     --query taskDefinition > task-definition.json

      # - name: Fill in the new image ID in the Amazon ECS task definition
      #   id: task-def
      #   uses: aws-actions/amazon-ecs-render-task-definition@79ad78d34a6ac6be9a9cd787056711e4b10c88d1
      #   with:
      #     task-definition: task-definition.json
      #     container-name: ${{ env.ECS_CONTAINER_NAME }}
      #     image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      # - name: Deploy Amazon ECS task definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@f2dce4be1c431cf5db770aec3991661fd9c62a19
      #   with:
      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
      #     cluster: ${{ env.ECS_CLUSTER }}
      #     service: ${{ env.ECS_SERVICE }}
      #     wait-for-service-stability: true
      #     codedeploy-appspec: appspec.json
      #     codedeploy-application: ${{ env.CODE_DEPLOY_APPLICATION }}
      #     codedeploy-deployment-group: ${{ env.CODE_DEPLOYMENT_GROUP }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_TITLE: GitHub Actions Build Result
          SLACK_COLOR: ${{ job.status }}

  deploy:
    if: ${{ github.event.inputs.job == 'deploy'}}
    runs-on: ubuntu-latest
    needs: static_check
    steps:
      - uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@ea7b857d8a33dc2fb4ef5a724500044281b49a5e
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Download existing task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_NAME }} \
          --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@79ad78d34a6ac6be9a9cd787056711e4b10c88d1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.ECS_CONTAINER_NAME }}
          image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@f2dce4be1c431cf5db770aec3991661fd9c62a19
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          cluster: ${{ env.ECS_CLUSTER }}
          service: ${{ env.ECS_SERVICE }}
          wait-for-service-stability: true
          codedeploy-appspec: appspec.json
          codedeploy-application: ${{ env.CODE_DEPLOY_APPLICATION }}
          codedeploy-deployment-group: ${{ env.CODE_DEPLOYMENT_GROUP }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        env:
          SLACK_TITLE: GitHub Actions Deployment Result
          SLACK_COLOR: ${{ job.status }}
